services:
  - type: web
    name: travel-buddy-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: OPENROUTER_API_KEY
        scope: build,runtime
      - key: PREDICTHQ_API_KEY
        scope: build,runtime
      - key: GOOGLE_API_KEY
        scope: build,runtime
      - key: GOOGLE_CX
        scope: build,runtime
      - key: NODE_ENV
        value: production
